version: '3.9'
services:

  backend:
    image: backend:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/crowdfundingDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=lab123
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  frontend:
    image: frontend:latest
    ports:
      - "3000:80"
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=crowdfundingDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lab123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

