name: Build and Push to DockerHub

on:
  push:
    branches: [ "master" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

  docker-build-and-push-backend:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./crowdfunding_backend
          push: true
          tags: kostadimitrovski/backend:latest

  docker-build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./crowdfunding_frontend
          push: true
          tags: kostadimitrovski/frontend:latest

